apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: "851725552187.dkr.ecr.eu-north-1.amazonaws.com/raz:service2"
          ports:
            - containerPort: 3001
          env:
              - name: MONGODB_URL
                value: "{{ .Values.mongodb.url }}"